### ISSUE TITLE
Latin Modern Mono 字型很難區分 '0' 和 'O'

### ISSUE THREAD

**Issue by syimyuzya** [nk2028/qieyun-autoderiver#1]
看上去並不是代碼字型呢…有點好奇選用這款字型的考慮

【順帶一提有套字型叫 [Iosevka](https://github.com/be5invis/Iosevka) 對 IPA 比較友好w

**Comment by syimyuzya** [comment]
【順帶一提，發現這個是因為系統恰好沒裝 Consolas 233

**Comment by sgalal** [comment]
咦，沒注意耶

當初是想着選一種有襯線的等寬字型

試了試 Iosevka，因為其他地方是有襯線的，所以感覺不是很搭

![Screenshot_20201124_093736](https://user-images.githubusercontent.com/32255369/100035486-458fd600-2e39-11eb-81f0-ae995884b930.png)

**Comment by syimyuzya** [comment]
壞耶 :joy:

話說 Iosevka 也有個 slab 體，是襯線體可以試下w

**Comment by sgalal** [comment]
由於 monospace 字型比較難選，#3 改為優先選用用户系統中的 monospace 字型，可以解決這個問題
