### ISSUE TITLE
“生”被推导为三等

### ISSUE THREAD

**Issue by kumoki** [nk2028/qieyun-autoderiver#15]
发现生被推导为了三等，加了行日志，得到的结果是
```json
{
    "母": "生",
    "呼": "開",
    "等": "三",
    "重紐": null,
    "韻": "庚",
    "聲": "平"
}
```
生是三等字吗，我记得我在其他多个地方看到过生是庚二，也可能我接触的资料旧了，能解释下吗？

**Comment by ayaka14732** [comment]
這個就是莊三化二

**Comment by kumoki** [comment]
邮件我已收到

**Comment by syimyuzya** [comment]
> 我记得我在其他多个地方看到过生是庚二

確實有些早年的資料會這樣處理，但其實考《切韻》（而非《廣韻》）同時期韻書「生」均為三等（反切比如「所京切」），《廣韻》的「所庚切」反映的是更往後時期的「莊三化二」的音。

本項目基於 Qieyun.js，既然是叫 Qieyun.js 而不叫 Guangyun.js 什麼的，即使預設資料基於《廣韻》一書，也理應校正為《切韻》音系的音。
