### ISSUE TITLE
Pronunciation to be corrected in the default article (滕王閣序)

### ISSUE THREAD

**Issue by syimyuzya** [nk2028/qieyun-autoderiver#18]
- 「并」當音平聲（《騰王閣序》的駢句句末是平仄交替的）
- 「眄」當音去聲（早期字書以去聲為首選音，也不一定收上聲）
- 「不」當音上聲（而訓讀為「弗」的音，當時尚未進入標準語）
- 「吳會」之「會」當音同「會稽」之「會」

（還有其他一些多音但義同的，可以暫不用校）

**Comment by ayaka14732** [comment]
「不」是因為當時我主要是想推導粵語 😂

**Comment by syimyuzya** [comment]
> 「不」是因為當時我主要是想推導粵語 :joy:

fau2 ✓ :laughing:

**Comment by syimyuzya** [comment]
Already fixed in both v0.1 & v0.2, closing
