### ISSUE TITLE
msoeg方案所庚切生小韵异常

### ISSUE THREAD

**Issue by Jiew-KuieJwiang** [nk2028/qieyun-autoderiver#6]
![image](https://user-images.githubusercontent.com/73825939/115184479-881bbd00-a110-11eb-903f-77656c363ea0.png)

**Comment by ayaka14732** [comment]
等寫好 msoeg 推導方案後即可修復

**Comment by Jeu-KyeJyeng** [comment]
![image](https://user-images.githubusercontent.com/73825939/115959607-8e120380-a53f-11eb-83f3-9b02e8c21fca.png)
新见许劣切异常

**Comment by ayaka14732** [comment]
還有幾個小韻異常，這些在數據中可以看到，等推導方案寫好後就可以全部修復

**Comment by untunt** [comment]
https://github.com/nk2028/qieyun-examples/pull/29
